# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooplisting',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cooplisting',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('PUBLISHED', 'Published'),
                    ('CLOSED', 'Closed'),
                    ('ARCHIVED', 'Archived'),
                ],
                default='PUBLISHED',
                max_length=20,
            ),
        ),
    ]
