# Generated by Django 4.2.16 on 2026-05-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnistory',
            name='story_category',
            field=models.CharField(choices=[('OUTSTANDING', 'Outstanding Alumni'), ('SUCCESS', 'Success Story')], default='SUCCESS', max_length=20),
        ),
    ]
