# Generated by Django 4.2.16 on 2026-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alumnistory_story_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('position', models.CharField(max_length=180)),
                ('short_description', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('education_level', models.CharField(blank=True, max_length=120)),
                ('cohort', models.CharField(blank=True, max_length=120)),
                ('field', models.CharField(blank=True, max_length=180)),
                ('major', models.CharField(blank=True, max_length=180)),
                ('avatar_url', models.URLField(blank=True)),
                ('content_vi', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]