# Generated by Django 4.2.16 on 2026-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_news_models_and_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnipost',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='alumnistory',
            name='featured_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='og_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='og_image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
