export const utilityNavigation = [
  {
    id: 'utility-contact',
    label: 'Hoa Sen 35 năm',
    path: 'https://www.hoasen.edu.vn/hoa-sen-35-nam/',
    external: true,
    target: '_blank',
    rel: 'noreferrer noopener',
    children: [],
    activeMatch: [],
    order: 1,
  },
  {
    id: 'utility-library',
    label: 'Cổng thông tin sinh viên',
    path: 'htttsv.hoasen.edu.vn/',
    external: true,
    target: '_blank',
    rel: 'noreferrer noopener',
    children: [],
    activeMatch: [],
    order: 2,
  },
];

export const mainNavigation = [
  {
    id: 'nav-home',
    label: 'Trang chủ',
    path: '/',
    external: false,
    target: '_self',
    rel: '',
    children: [],
    activeMatch: ['/'],
    order: 1,
  },
  {
    id: 'nav-about',
    label: 'Giới thiệu',
    path: '/gioi-thieu/dinh-huong-hoat-dong',
    external: false,
    target: '_self',
    rel: '',
    activeMatch: ['/gioi-thieu'],
    order: 2,
    children: [
      {
        id: 'nav-about-direction',
        label: 'Định hướng hoạt động',
        path: '/gioi-thieu/dinh-huong-hoat-dong',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/gioi-thieu/dinh-huong-hoat-dong'],
        order: 1,
      },
    ],
  },
  {
    id: 'nav-news-events',
    label: 'Tin tức & Sự kiện',
    path: '/tin-tuc',
    external: false,
    target: '_self',
    rel: '',
    activeMatch: ['/tin-tuc', '/su-kien'],
    order: 3,
    children: [
      {
        id: 'nav-news',
        label: 'Tin tức',
        path: '/tin-tuc',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/tin-tuc'],
        order: 1,
      },
      {
        id: 'nav-events',
        label: 'Sự kiện',
        path: '/su-kien',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/su-kien'],
        order: 2,
      },
    ],
  },
  {
    id: 'nav-community',
    label: 'Cộng đồng Alumni',
    path: '/cong-dong-alumni',
    external: false,
    target: '_self',
    rel: '',
    activeMatch: ['/cong-dong-alumni'],
    order: 4,
    children: [
      {
        id: 'nav-community-directory',
        label: 'Trang cộng đồng alumni',
        path: '/cong-dong-alumni',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni'],
        order: 1,
      },
      {
        id: 'nav-community-policy',
        label: 'Chính sách Alumni',
        path: '/cong-dong-alumni/chinh-sach-alumni',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/chinh-sach-alumni'],
        order: 2,
      },
      {
        id: 'nav-community-board',
        label: 'Thông tin ban liên lạc',
        path: '/cong-dong-alumni/ban-lien-lac',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/ban-lien-lac'],
        order: 3,
      },
      {
        id: 'nav-community-outstanding',
        label: 'Cựu sinh viên tiêu biểu',
        path: '/cong-dong-alumni/cuu-sinh-vien-tieu-bieu',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/cuu-sinh-vien-tieu-bieu'],
        order: 4,
      },
      {
        id: 'nav-community-success',
        label: 'Câu chuyện thành công',
        path: '/cong-dong-alumni/cau-chuyen-thanh-cong',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/cau-chuyen-thanh-cong'],
        order: 5,
      },
      {
        id: 'nav-community-gallery',
        label: 'Thư viện hình ảnh',
        path: '/cong-dong-alumni/thu-vien-hinh-anh',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/thu-vien-hinh-anh'],
        order: 6,
      },
    ],
  },
  {
    id: 'nav-career',
    label: 'Việc làm & Kết nối',
    path: 'https://career.hoasen.edu.vn/',
    external: true,
    target: '_blank',
    rel: 'noreferrer noopener',
    activeMatch: [],
    order: 5,
    children: [
      {
        id: 'nav-career-opportunities',
        label: 'Cơ hội việc làm',
        path: '/viec-lam-ket-noi/hoa-sen-job',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: [],
        order: 1,
      },
      {
        id: 'nav-career-webinars',
        label: 'Career Webinars',
        path: '/viec-lam-ket-noi/career-webinars',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/viec-lam-ket-noi/career-webinars'],
        order: 2,
      },
      {
        id: 'nav-career-post',
        label: 'Đăng tin tuyển dụng',
        path: '/viec-lam-ket-noi/dang-tin-tuyen-dung',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: [],
        order: 3,
      },
    ],
  },
  {
    id: 'nav-services',
    label: 'Dịch vụ Alumni',
    path: '/dich-vu-alumni/hoa-sen-coop',
    external: false,
    target: '_self',
    rel: '',
    activeMatch: ['/dich-vu-alumni'],
    order: 6,
    children: [
      {
        id: 'nav-services-coop',
        label: 'Hoa Sen COOP',
        path: '/dich-vu-alumni/hoa-sen-coop',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/dich-vu-alumni/hoa-sen-coop'],
        order: 1,
      },
      {
        id: 'nav-services-shop',
        label: 'Hoa Sen Shop',
        path: '/dich-vu-alumni/hoa-sen-shop',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/dich-vu-alumni/hoa-sen-shop'],
        order: 2,
      },
      {
        id: 'nav-services-courses',
        label: 'Hoa Sen Courses',
        path: '/dich-vu-alumni/hoa-sen-courses',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/dich-vu-alumni/hoa-sen-courses'],
        order: 3,
      },
      {
        id: 'nav-services-library',
        label: 'Thư viện Hoa Sen',
        path: 'https://library.hoasen.edu.vn/',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 4,
      },
      {
        id: 'nav-services-facilities',
        label: 'Hỗ trợ Cơ sở vật chất',
        path: 'https://www.hoasen.edu.vn/so-tay-sinh-vien/trai-nghiem-co-so-hoc-tap/',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 5,
      },
    ],
  },
];