export const utilityNavigation = [
  {
    id: 'utility-library',
    label: 'Thư viện',
    path: 'https://library.hoasen.edu.vn/',
    external: true,
    target: '_blank',
    rel: 'noreferrer noopener',
    children: [],
    activeMatch: [],
    order: 1,
  },
  {
    id: 'utility-contact',
    label: 'Liên hệ',
    path: 'https://www.hoasen.edu.vn/lien-he/',
    external: true,
    target: '_blank',
    rel: 'noreferrer noopener',
    children: [],
    activeMatch: [],
    order: 2,
  },
];

export const mainNavigation = [
  {
    id: 'nav-home',
    label: 'Trang chủ',
    path: '/',
    external: false,
    target: '_self',
    rel: '',
    children: [],
    activeMatch: ['/'],
    order: 1,
  },
  {
    id: 'nav-about',
    label: 'Giới thiệu',
    path: '/gioi-thieu/dinh-huong-hoat-dong',
    external: false,
    target: '_self',
    rel: '',
    activeMatch: ['/gioi-thieu'],
    order: 2,
    children: [
      {
        id: 'nav-about-direction',
        label: 'Định hướng hoạt động',
        path: '/gioi-thieu/dinh-huong-hoat-dong',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/gioi-thieu/dinh-huong-hoat-dong'],
        order: 1,
        description: 'Trang nội dung về định hướng, sứ mệnh và cách HSU Alumni kết nối cộng đồng.',
      },
    ],
  },
  {
    id: 'nav-news-events',
    label: 'Tin tức & Sự kiện',
    path: 'https://www.hoasen.edu.vn/tin-tuc/',
    external: true,
    target: '_blank',
    rel: 'noreferrer noopener',
    activeMatch: [],
    order: 3,
    children: [
      {
        id: 'nav-news',
        label: 'Tin tức',
        path: 'https://www.hoasen.edu.vn/tin-tuc/',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 1,
        description: 'External link tới khu vực Tin tức chính thức của Đại học Hoa Sen.',
      },
      {
        id: 'nav-events',
        label: 'Sự kiện',
        path: 'https://www.hoasen.edu.vn/event/',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 2,
        description: 'External link tới lịch sự kiện chính thức của Đại học Hoa Sen.',
      },
    ],
  },
  {
    id: 'nav-community',
    label: 'Cộng đồng Alumni',
    path: '/cong-dong-alumni/chinh-sach-alumni',
    external: false,
    target: '_self',
    rel: '',
    activeMatch: ['/cong-dong-alumni'],
    order: 4,
    children: [
      {
        id: 'nav-community-policy',
        label: 'Chính sách Alumni',
        path: '/cong-dong-alumni/chinh-sach-alumni',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/chinh-sach-alumni'],
        order: 1,
        description: 'Trang chính sách, quyền lợi và nguyên tắc tham gia mạng lưới Alumni.',
      },
      {
        id: 'nav-community-board',
        label: 'Thông tin ban liên lạc',
        path: '/cong-dong-alumni/ban-lien-lac',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/ban-lien-lac'],
        order: 2,
        description: 'Thông tin đầu mối, ban liên lạc và các kênh kết nối chính thức.',
      },
      {
        id: 'nav-community-outstanding',
        label: 'Cựu sinh viên tiêu biểu',
        path: '/cong-dong-alumni/cuu-sinh-vien-tieu-bieu',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/cuu-sinh-vien-tieu-bieu'],
        order: 3,
        description: 'Danh mục gương mặt Alumni tiêu biểu và câu chuyện truyền cảm hứng.',
      },
      {
        id: 'nav-community-success',
        label: 'Câu chuyện thành công',
        path: '/cong-dong-alumni/cau-chuyen-thanh-cong',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/cau-chuyen-thanh-cong'],
        order: 4,
        description: 'Nơi kể lại những hành trình nghề nghiệp và tác động tích cực từ Alumni.',
      },
      {
        id: 'nav-community-gallery',
        label: 'Thư viện hình ảnh',
        path: '/cong-dong-alumni/thu-vien-hinh-anh',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/cong-dong-alumni/thu-vien-hinh-anh'],
        order: 5,
        description: 'Album hình ảnh hoạt động, sự kiện và dấu ấn cộng đồng Alumni.',
      },
    ],
  },
  {
    id: 'nav-career',
    label: 'Việc làm & Kết nối',
    path: 'https://career.hoasen.edu.vn/',
    external: true,
    target: '_blank',
    rel: 'noreferrer noopener',
    activeMatch: [],
    order: 5,
    children: [
      {
        id: 'nav-career-opportunities',
        label: 'Cơ hội việc làm',
        path: 'https://career.hoasen.edu.vn/',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 1,
        description: 'External link tới nền tảng career chính thức của hệ sinh thái HSU.',
      },
      {
        id: 'nav-career-webinars',
        label: 'Career Webinars',
        path: 'https://career.hoasen.edu.vn/tin-tuc-35A52D92',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 2,
        description: 'External link tới khu vực webinar và tin tức nghề nghiệp.',
      },
      {
        id: 'nav-career-post',
        label: 'Đăng tin tuyển dụng',
        path: 'https://career.hoasen.edu.vn/tin-tuc-35A52D92',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 3,
        description: 'External link theo navigation hiện tại; cần stakeholder chốt với module Job nội bộ.',
      },
    ],
  },
  {
    id: 'nav-services',
    label: 'Dịch vụ Alumni',
    path: '/dich-vu-alumni/hoa-sen-coop',
    external: false,
    target: '_self',
    rel: '',
    activeMatch: ['/dich-vu-alumni'],
    order: 6,
    children: [
      {
        id: 'nav-services-coop',
        label: 'Hoa Sen COOP',
        path: '/dich-vu-alumni/hoa-sen-coop',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/dich-vu-alumni/hoa-sen-coop'],
        order: 1,
        description: 'Sàn kết nối sản phẩm, dịch vụ và ưu đãi từ cộng đồng Alumni.',
      },
      {
        id: 'nav-services-shop',
        label: 'Hoa Sen Shop',
        path: '/dich-vu-alumni/hoa-sen-shop',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/dich-vu-alumni/hoa-sen-shop'],
        order: 2,
        description: 'Landing page dịch vụ Shop dành cho Alumni, chờ hoàn thiện nội dung nghiệp vụ.',
      },
      {
        id: 'nav-services-courses',
        label: 'Hoa Sen Courses',
        path: '/dich-vu-alumni/hoa-sen-courses',
        external: false,
        target: '_self',
        rel: '',
        children: [],
        activeMatch: ['/dich-vu-alumni/hoa-sen-courses'],
        order: 3,
        description: 'Landing page ưu đãi học tập và lộ trình phát triển dành cho Alumni.',
      },
      {
        id: 'nav-services-library',
        label: 'Thư viện Hoa Sen',
        path: 'https://library.hoasen.edu.vn/',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 4,
        description: 'External link tới thư viện chính thức của Hoa Sen University.',
      },
      {
        id: 'nav-services-facilities',
        label: 'Hỗ trợ Cơ sở vật chất',
        path: 'https://www.hoasen.edu.vn/so-tay-sinh-vien/trai-nghiem-co-so-hoc-tap/',
        external: true,
        target: '_blank',
        rel: 'noreferrer noopener',
        children: [],
        activeMatch: [],
        order: 5,
        description: 'External link tới thông tin hỗ trợ cơ sở vật chất và trải nghiệm học tập.',
      },
    ],
  },
];