# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='employment_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='work_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
